"""Create links table.

Revision ID: 0001
Revises:
Create Date: 2026-10-05

Expand/contract phase: expand (new table only; no existing code depends on it).

Hand-written rather than autogenerated (no database was available to diff
against). `alembic check` confirms it matches shortener.models.Link.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None  # first migration
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "links",
        # Surrogate key. GENERATED ALWAYS AS IDENTITY (not SERIAL) rejects
        # manually supplied ids, so the sequence can never drift.
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        # Short code used in the public URL: generated (7 chars) or a custom
        # alias (3-32 chars). Length must match models.CODE_MAX_LENGTH.
        sa.Column("code", sa.String(length=32), nullable=False),
        # Redirect destination. TEXT because URLs have no useful fixed bound;
        # the API caps them at 2048 characters.
        sa.Column("target_url", sa.Text(), nullable=False),
        # All timestamps are timezone-aware (stored as UTC by Postgres).
        # The database sets created_at, so it doesn't depend on app clocks.
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # NULL means the link never expires.
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        # Incremented atomically in the redirect query (click_count + 1).
        # A server default means inserts never have to supply it.
        sa.Column("click_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        # NULL until the first redirect.
        sa.Column("last_clicked_at", sa.DateTime(timezone=True), nullable=True),
        # Constraint names come from op.f() so they match the naming convention
        # in models.py exactly; later migrations can refer to them by name.
        sa.CheckConstraint("click_count >= 0", name=op.f("ck_links_click_count_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_links")),
        # Enforces alias uniqueness. The API relies on this constraint (not a
        # read-before-insert) to return 409, so concurrent creates are safe.
        # It also provides the index used for code lookups.
        sa.UniqueConstraint("code", name=op.f("uq_links_code")),
    )


def downgrade() -> None:
    # Destroys all links. Only safe because this is the first migration; never
    # run it against a database whose data you want to keep.
    op.drop_table("links")
